# Generated by Django 3.1.7 on 2021-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('maincourse', 'MAINCOURSE'), ('appetizer', 'APPETIZER'), ('salad', 'SALAD'), ('desserts', 'DESSERTS'), ('beverage', 'BEVERAGE')], max_length=30),
        ),
    ]
