# Generated by Django 3.1.6 on 2021-02-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofs', '0003_dessert_item_orderdetail_salad'),
    ]

    operations = [
        migrations.AddField(
            model_name='appetizer',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salad',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
