# Generated by Django 3.1.6 on 2021-02-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofs', '0004_auto_20210214_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetail', to='ofs.customer'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
